name: Build, Update, and Convert

on:
  workflow_dispatch:
    inputs:
      backup_filename:
        description: 'Nama file backup yang akan dikonversi (misalnya: backup.tcbk)'
        required: true
        default: 'backup.tcbk'

jobs:
  build-update-convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build nekotatsu
        run: cargo build --release

      - name: Upload test backup (jika tersedia di repo)
        if: exists('backup/${{ github.event.inputs.backup_filename }}')
        uses: actions/upload-artifact@v4
        with:
          name: backup
          path: backup/${{ github.event.inputs.backup_filename }}

      - name: Download backup artifact
        uses: actions/download-artifact@v4
        with:
          name: backup
          path: ./backup

      - name: Jalankan nekotatsu update
        run: |
          ./target/release/nekotatsu update \
            --tachi-link https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json \
            --kotatsu-link https://github.com/KotatsuApp/kotatsu-parsers/archive/refs/heads/master.zip

      - name: Konversi backup ke Kotatsu
        run: |
          ./target/release/nekotatsu convert backup/${{ github.event.inputs.backup_filename }} \
            -o converted-output.json

      - name: Clean build
        run: cargo clean
  
      - name: Upload hasil konversi
        uses: actions/upload-artifact@v4
        with:
          name: converted-output
          path: converted-output.json