name: Build, Update, and Convert

on:
  workflow_dispatch:

jobs:
  build-update-convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository ini
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build nekotatsu
        run: cargo build --release

      - name: Download backup file dari mozzaru/nekotatsu (via raw link)
        run: |
          mkdir -p backup
          curl -L \
            -o backup/app.tachibk \
            https://github.com/mozzaru/nekotatsu/raw/refs/heads/master/app.mihon_2025-05-11_21-33.tachibk

      - name: Jalankan nekotatsu update
        run: |
          ./target/release/nekotatsu update \
            --tachi-link https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json \
            --kotatsu-link https://github.com/KotatsuApp/kotatsu-parsers/archive/refs/heads/master.zip

      - name: Konversi backup ke Kotatsu
        run: |
          ./target/release/nekotatsu convert backup/app.tachibk \
            -o converted-output.zip

      - name: Validasi file output
        run: |
          if [ -f converted-output.zip ]; then
            echo "File output ditemukan."
          else
            echo "File output TIDAK ditemukan."
            exit 1
          fi

      - name: Upload hasil konversi
        uses: actions/upload-artifact@v4
        with:
          name: converted-output
          path: converted-output.zip

      - name: Clean build
        run: cargo clean